USE MY_SQL_QUERRY
DROP TABLE EMPLOYEE
CREATE TABLE EMPLOYEE(SRNO INT PRIMARY KEY,NAME VARCHAR(255),ADDRESS VARCHAR(255),POSITION VARCHAR(255));
SELECT * FROM EMPLOYEE
ALTER TABLE EMPLOYEE MODIFY COLUMN SRNO INT AUTO_INCREMENT
INSERT INTO EMPLOYEE (NAME,ADDRESS,POSITION) 
VALUES("POOJA","UP","GUI DEVELOPER"),("PRYA","GOA",".NET");

select count(*)from employee

