USE MY_SQL_QUERRY;
CREATE TABLE EMP(
ID INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(50),
AGE INT);

CREATE TABLE EMP_AUDIT(
ID INT PRIMARY KEY AUTO_INCREMENT,
AUDIT_DISCRIPTION VARCHAR(500));

select * from EMP;
select * from EMP_AUDIT

insert into emp values(null ,'RAJVIR',6);
UPDATE EMP SET NAME ="TEJASHRI KALBHOR" WHERE ID =1

DELETE FROM EMP WHERE ID =5;

