USE MY_SQL_QUERRY;
 SET GLOBAL log_bin_trust_function_creators = 1;
DELIMITER //
CREATE FUNCTION MY_MESSAGE()
RETURNS VARCHAR(50)
BEGIN
   RETURN 'WELCOME TO THE FUNCTIONS';
END //
DELIMITER ;

SELECT MY_MESSAGE();