USE MY_SQL_QUERRY;
 SET GLOBAL log_bin_trust_function_creators = 1;
DELIMITER //
CREATE FUNCTION MY_MESSAGE()
RETURNS VARCHAR(50)
BEGIN
   RETURN 'WELCOME TO THE FUNCTIONS';
END //
DELIMITER ;

SELECT MY_MESSAGE();

-- PARAMETERS
DELIMITER //
CREATE FUNCTION MY_PARAMS(FIRST_NAME VARCHAR(255),LAST_NAME VARCHAR(255))
RETURNS VARCHAR(255)
BEGIN
RETURN CONCAT(FIRST_NAME,' ',LAST_NAME);
END //
DELIMITER ;
SELECT MY_PARAMS('TEJASHRI','KALBHOR')AS FULLNAME

-- ADDITION OF 2 NUM

DELIMITER //
CREATE FUNCTION ADDITION(NUM1 INT , NUM2 INT)
RETURNS INT
BEGIN
RETURN NUM1 + NUM2;
END //
DELIMITER ;
SELECT ADDITION(10,20);

-- CALCULATE AGE
DELIMITER //
CREATE FUNCTION CALCULATE_AGE(DOB DATE)
RETURNS INT
BEGIN
DECLARE TODAY_DATE DATE;
SELECT CURRENT_DATE() INTO TODAY_DATE;
RETURN YEAR(TODAY_DATE) - YEAR(DOB);
END //
DELIMITER ;

SELECT CALCULATE_AGE('1998-02-04') AS 'YOUR_AGE';
SHOW FUNCTION STATUS WHERE DB ='MY_SQL_QUERRY';
