USE MY_SQL_QUERRY;
CREATE TABLE STUDENT(SRNO INT(5),NAME VARCHAR(15),ADDRESS VARCHAR(20),MOBILE_NO INT(10),MARKS INT(3));

INSERT INTO STUDENT VALUES(2,"TEJ","PUNE",912345671,70);
SELECT SRNO,NAME FROM STUDENT;