USE MY_SQL_QUERRY
-- WE ARE TAKING INPUT PARAMETERS USING IN OPERATOR
DELIMITER //
CREATE PROCEDURE SP_PARAMS(IN EMPNAME VARCHAR(255))
BEGIN
SELECT * FROM EMPLOYEE WHERE NAME = EMPNAME ;
END //
DELIMITER ;
CALL SP_PARAMS('TEJASHRI')

--WITHOUT IN OPERATOR
DELIMITER //
CREATE PROCEDURE SP_PARAM(EMP_POSITION VARCHAR(255))
BEGIN
SELECT * FROM EMPLOYEE WHERE POSITION = EMP_POSITION ;
END //
DELIMITER ;
CALL  SP_PARAM('ASSOCIATE SOFTWARE ENGINEER');

-- WITH IF ELSE CONDITION
DELIMITER //
CREATE PROCEDURE SP_CONDITION(NUM INT(3))
BEGIN
IF NUM % 2 = 0 THEN
SELECT 'NUMBER IS EVEN' AS RESULT;
ELSE
SELECT 'NUMBER IS ODD' AS RESULT;
END IF ;
END //
DELIMITER ;
CALL  SP_CONDITION(5);
 
 