DELIMITER //
CREATE PROCEDURE MY_PROC_EMP()
BEGIN
SELECT * FROM EMPLOYEE WHERE ADDRESS NOT IN "PUNE";
END //
DELIMITER ;

CALL   MY_PROC_EMP()

DELIMITER //
CREATE PROCEDURE MY_PROC_EMPADD()
BEGIN
SELECT * FROM EMPLOYEE WHERE ADDRESS <>'PUNE';
END //
DELIMITER ;

CALL   MY_PROC_EMPADD();
