USE MY_SQL_QUERRY;

DELIMITER //
CREATE TRIGGER TR_AFTER_INSERT_EMP
AFTER INSERT ON EMP 
FOR EACH ROW
BEGIN
INSERT INTO EMP_AUDIT VALUES(NULL,CONCAT('A ROW IS INSERTED IN EMP TABLE AT ',DATE_FORMAT(NOW(),'%d-%m-%y %h:%i:%s %p')));
END //
DELIMITER ;

-- AFTER INSERT BY USING NEW KEYWORD TO 
DELIMITER //
CREATE TRIGGER TR_AFTER_INSERT_EMP_TABLE
AFTER INSERT ON EMP 
FOR EACH ROW
BEGIN
DECLARE EMP_ID INT;
SET EMP_ID = NEW.ID;
INSERT INTO EMP_AUDIT VALUES(NULL,CONCAT('A ROW IS INSERTED IN EMP TABLE AT WITH ID ', EMP_ID , DATE_FORMAT(NOW(),' %d-%m-%y %h:%i:%s %p')));
END //
DELIMITER ;

DROP TRIGGER TR_AFTER_INSERT_EMP_TABLE

-- AFTER DELETE 
DELIMITER //
CREATE TRIGGER TR_AFTER_DELETE_EMP_TABLE
AFTER DELETE ON EMP 
FOR EACH ROW
BEGIN
DECLARE EMP_ID INT;
SET EMP_ID = OLD.ID;
INSERT INTO EMP_AUDIT VALUES(NULL,CONCAT('A ROW IS DELETED IN EMP TABLE AT WITH ID ', EMP_ID , DATE_FORMAT(NOW(),' %d-%m-%y %h:%i:%s %p')));
END //
DELIMITER ;

-- AFTER UPDATE

DELIMITER //
CREATE TRIGGER TR_AFTER_UPDATE_EMP_TABLE
AFTER UPDATE ON EMP 
FOR EACH ROW
BEGIN
DECLARE UPDATE_EMP_NAME VARCHAR(255);
DECLARE DELETE_EMP_NAME VARCHAR(255);
SET UPDATE_EMP_NAME  = NEW.NAME;
SET DELETE_EMP_NAME  = OLD.NAME;
INSERT INTO EMP_AUDIT VALUES(NULL,CONCAT('A ROW WITH COLUMN NAME ', DELETE_EMP_NAME ,' IS REPLACED WITH ', UPDATE_EMP_NAME ,DATE_FORMAT(NOW(),' %d-%m-%y %h:%i:%s %p')));
END //
DELIMITER ;
DROP TRIGGER TR_AFTER_UPDATE_EMP_TABLE;

-- BEFORE INSERT

DELIMITER //
CREATE TRIGGER TR_BEFORE_INSERT_EMP_TABLE
BEFORE INSERT ON EMP
FOR EACH ROW 
BEGIN
DECLARE EMP_AGE INT;
SET EMP_AGE = NEW.AGE;
IF EMP_AGE < 18 THEN
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT ='YOU ARE NOT ELIGIBLE' ;
END IF ;
END //
DELIMITER ;

